const tutors = [
    {
        firstName: "John",
        lastName: "Doe",
        country: "USA",
        language: "English",
        price: 20,
        summary: "Experienced tutor with 5 years of teaching English.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.5,
    },
    {
        firstName: "Maria",
        lastName: "Gonzalez",
        country: "Mexico",
        language: "Spanish",
        price: 15,
        summary: "Native Spanish speaker specializing in beginner to advanced levels.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.7,
    },
    {
        firstName: "Ahmed",
        lastName: "Khan",
        country: "Pakistan",
        language: "Urdu",
        price: 12,
        summary: "Fluent in Urdu and teaching for over 3 years.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.2,
    },
    {
        firstName: "Sofia",
        lastName: "Ivanova",
        country: "Russia",
        language: "Russian",
        price: 18,
        summary: "Russian tutor with a passion for helping students achieve fluency.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.8,
    },
    {
        firstName: "Chen",
        lastName: "Li",
        country: "China",
        language: "Mandarin",
        price: 22,
        summary: "Certified Mandarin tutor with 6 years of experience.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.9,
    },
    {
        firstName: "Emily",
        lastName: "Brown",
        country: "Canada",
        language: "French",
        price: 25,
        summary: "Native French speaker helping students with conversational French.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.6,
    },
    {
        firstName: "Hassan",
        lastName: "Ali",
        country: "Egypt",
        language: "Arabic",
        price: 20,
        summary: "Passionate Arabic tutor focused on grammar and conversation.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.4,
    },
    {
        firstName: "Mei",
        lastName: "Yamamoto",
        country: "Japan",
        language: "Japanese",
        price: 30,
        summary: "Specialized in teaching Japanese to beginners and intermediates.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.7,
    },
    {
        firstName: "Liam",
        lastName: "Smith",
        country: "UK",
        language: "English",
        price: 18,
        summary: "Focuses on IELTS preparation and business English.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.3,
    },
    {
        firstName: "Fatima",
        lastName: "Hassan",
        country: "Morocco",
        language: "Arabic",
        price: 15,
        summary: "Teaches both classical Arabic and Moroccan dialect.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.5,
    },
];

export default tutors;
