const tutors = [
    {
        id: 0,
        firstName: "John",
        lastName: "Doe",
        country: "USA",
        language: "English",
        price: 20,
        summary: "Experienced tutor with 5 years of teaching English.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.5,
    },
    {
        id: 1,
        firstName: "Maria",
        lastName: "Gonzalez",
        country: "Mexico",
        language: "Spanish",
        price: 15,
        summary: "Native Spanish speaker specializing in beginner to advanced levels.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.7,
    },
    {
        id: 2,
        firstName: "Ahmed",
        lastName: "Khan",
        country: "Pakistan",
        language: "Urdu",
        price: 12,
        summary: "Fluent in Urdu and teaching for over 3 years.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.2,
    },
    {
        id: 3,
        firstName: "Sofia",
        lastName: "Ivanova",
        country: "Russia",
        language: "Russian",
        price: 18,
        summary: "Russian tutor with a passion for helping students achieve fluency.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.8,
    },
    {
        id: 4,
        firstName: "Chen",
        lastName: "Li",
        country: "China",
        language: "Mandarin",
        price: 22,
        summary: "Certified Mandarin tutor with 6 years of experience.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.9,
    },
    {
        id: 5,
        firstName: "Emily",
        lastName: "Brown",
        country: "Canada",
        language: "French",
        price: 25,
        summary: "Native French speaker helping students with conversational French.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.6,
    },
    {
        id: 6,
        firstName: "Hassan",
        lastName: "Ali",
        country: "Egypt",
        language: "Arabic",
        price: 20,
        summary: "Passionate Arabic tutor focused on grammar and conversation.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.4,
    },
    {
        id: 7,
        firstName: "Mei",
        lastName: "Yamamoto",
        country: "Japan",
        language: "Japanese",
        price: 30,
        summary: "Specialized in teaching Japanese to beginners and intermediates.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.7,
    },
    {
        id: 8,
        firstName: "Liam",
        lastName: "Smith",
        country: "UK",
        language: "English",
        price: 18,
        summary: "Focuses on IELTS preparation and business English.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.3,
    },
    {
        id: 9,
        firstName: "Fatima",
        lastName: "Hassan",
        country: "Morocco",
        language: "Arabic",
        price: 15,
        summary: "Teaches both classical Arabic and Moroccan dialect.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.5,
    },
    {
        id: 10,
        firstName: "Ali",
        lastName: "Mahmoud",
        country: "Saudi Arabia",
        language: "Arabic",
        price: 18,
        summary: "Native Arabic speaker specializing in Quranic and modern Arabic.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.7,
    },
    {
        id: 11,
        firstName: "Zara",
        lastName: "Omar",
        country: "UAE",
        language: "Arabic",
        price: 20,
        summary: "Teaches classical Arabic and conversational Emirati dialect.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.8,
    },
    {
        id: 12,
        firstName: "Jacob",
        lastName: "Williams",
        country: "USA",
        language: "English",
        price: 25,
        summary: "Expert in teaching English for business and academic purposes.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.9,
    },
    {
        id: 13,
        firstName: "Layla",
        lastName: "Al-Farsi",
        country: "Oman",
        language: "Arabic",
        price: 17,
        summary: "Focuses on teaching Omani dialect and modern Arabic literature.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.6,
    },
    {
        id: 14,
        firstName: "Maria",
        lastName: "Fernandez",
        country: "Spain",
        language: "Spanish",
        price: 15,
        summary: "Experienced tutor for conversational Spanish and grammar.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.5,
    },
    {
        id: 15,
        firstName: "Adnan",
        lastName: "Rahman",
        country: "Bangladesh",
        language: "Bengali",
        price: 12,
        summary: "Teaches Bengali language and culture to beginners and advanced learners.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.2,
    },
    {
        id: 16,
        firstName: "Fatimah",
        lastName: "Khalil",
        country: "Jordan",
        language: "Arabic",
        price: 19,
        summary: "Specialist in teaching spoken Levantine Arabic and Arabic calligraphy.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.7,
    },
    {
        id: 17,
        firstName: "Youssef",
        lastName: "El-Baz",
        country: "Egypt",
        language: "Arabic",
        price: 14,
        summary: "Focuses on Quranic recitation and classical Arabic grammar.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.8,
    },
    {
        id: 18,
        firstName: "Hiroshi",
        lastName: "Tanaka",
        country: "Japan",
        language: "Japanese",
        price: 28,
        summary: "Experienced tutor in Japanese writing and cultural nuances.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.6,
    },
    {
        id: 19,
        firstName: "Chen",
        lastName: "Zhang",
        country: "China",
        language: "Mandarin",
        price: 22,
        summary: "Specialist in teaching Mandarin for beginners and advanced learners.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.9,
    },
    {
        id: 20,
        firstName: "Aisha",
        lastName: "Mohamed",
        country: "Sudan",
        language: "Arabic",
        price: 13,
        summary: "Helps students learn Sudanese Arabic and formal Arabic conversation.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.5,
    },
    {
        id: 21,
        firstName: "Ethan",
        lastName: "Walker",
        country: "UK",
        language: "English",
        price: 20,
        summary: "Experienced IELTS and TOEFL coach with high success rates.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.8,
    },
    {
        id: 22,
        firstName: "Sahar",
        lastName: "Al-Mutairi",
        country: "Kuwait",
        language: "Arabic",
        price: 18,
        summary: "Teaches Kuwaiti dialect and formal Arabic with interactive methods.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.6,
    },
    {
        id: 23,
        firstName: "Liam",
        lastName: "Murphy",
        country: "Ireland",
        language: "English",
        price: 24,
        summary: "Focuses on teaching English with a focus on pronunciation and grammar.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.7,
    },
    {
        id: 24,
        firstName: "Sara",
        lastName: "Al-Ali",
        country: "Lebanon",
        language: "Arabic",
        price: 16,
        summary: "Teaches Lebanese dialect and beginner Arabic grammar.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.5,
    },
    {
        id: 25,
        firstName: "Diego",
        lastName: "Ruiz",
        country: "Colombia",
        language: "Spanish",
        price: 15,
        summary: "Specialist in conversational Spanish for travelers and business professionals.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.7,
    },
    {
        id: 26,
        firstName: "Jamal",
        lastName: "Nasir",
        country: "Morocco",
        language: "Arabic",
        price: 17,
        summary: "Teaches Moroccan dialect and classical Arabic for all levels.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.8,
    },
    {
        id: 27,
        firstName: "Aliyah",
        lastName: "Farah",
        country: "Somalia",
        language: "Somali",
        price: 12,
        summary: "Experienced tutor in Somali language and culture.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.4,
    },
    {
        id: 28,
        firstName: "Noor",
        lastName: "Hameed",
        country: "Iraq",
        language: "Arabic",
        price: 18,
        summary: "Teaches Iraqi Arabic with focus on conversational skills.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.6,
    },
    {
        id: 29,
        firstName: "Samuel",
        lastName: "Johnson",
        country: "USA",
        language: "English",
        price: 22,
        summary: "Business English coach with 8 years of experience.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.9,
    },
    {
        id: 30,
        firstName: "Amina",
        lastName: "Yousef",
        country: "Palestine",
        language: "Arabic",
        price: 15,
        summary: "Expert in teaching Palestinian dialect and formal Arabic writing.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.7,
    },
    {
        id: 31,
        firstName: "Carlos",
        lastName: "Silva",
        country: "Brazil",
        language: "Portuguese",
        price: 14,
        summary: "Helps students master conversational Portuguese and grammar basics.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.6,
    },
    {
        id: 32,
        firstName: "Meera",
        lastName: "Ravi",
        country: "India",
        language: "Hindi",
        price: 12,
        summary: "Fluent Hindi tutor with a passion for teaching cultural nuances.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.4,
    },
    {
        id: 33,
        firstName: "Anastasia",
        lastName: "Volkova",
        country: "Ukraine",
        language: "Russian",
        price: 18,
        summary: "Native Russian speaker helping students achieve fluency in all skills.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.8,
    },
    {
        id: 34,
        firstName: "William",
        lastName: "Brown",
        country: "South Africa",
        language: "English",
        price: 20,
        summary: "IELTS and TOEFL specialist with experience in academic English.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.7,
    },
    {
        id: 35,
        firstName: "Aya",
        lastName: "Farouk",
        country: "Algeria",
        language: "Arabic",
        price: 16,
        summary: "Teaches Algerian Arabic and cultural history with interactive lessons.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.5,
    },
    {
        id: 36,
        firstName: "Jean-Pierre",
        lastName: "Dubois",
        country: "France",
        language: "French",
        price: 25,
        summary: "Native French tutor focusing on advanced conversational skills.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.9,
    },
    {
        id: 37,
        firstName: "Thandiwe",
        lastName: "Ndlovu",
        country: "Zimbabwe",
        language: "Shona",
        price: 10,
        summary: "Teaches Shona language and Zimbabwean culture to all levels.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.3,
    },
    {
        id: 38,
        firstName: "Mats",
        lastName: "Johansson",
        country: "Sweden",
        language: "Swedish",
        price: 22,
        summary: "Teaches Swedish for business professionals and travelers.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.8,
    },
    {
        id: 39,
        firstName: "Hafsa",
        lastName: "Suleiman",
        country: "Nigeria",
        language: "Hausa",
        price: 14,
        summary: "Native Hausa tutor helping students learn both language and culture.",
        avatar: "https://via.placeholder.com/150",
        rating: 4.6,
    },

];

export default tutors;
